### ISSUE TITLE
postMessage跨域

### ISSUE THREAD

**Issue by Pzhicong** [FatDong1/cross-domain-demo#3]
reqIndex页面会循环调用receiveMessage方法，不停

**Comment by rudyxu1102** [comment]
hello，我刚才试了一下，没有出现不停调用这个方法的情况，可以说具体一点吗？最好有截图和错误原因。

**Comment by Pzhicong** [comment]
![qq 20170808172619](https://user-images.githubusercontent.com/13126996/29065466-c01a56a6-7c5e-11e7-98d8-2140fd7ddd1e.png)
上图console方法会一直执行哦

**Comment by rudyxu1102** [comment]
![postMessage](http://chuantu.biz/t5/164/1502185180x992607480.gif)

我在req里面的index.html中的receiveMessage中加入`console.log(event, '3000')`，在localhost:3000访问是这样的情况，有什么不一样的吗
