### ISSUE TITLE
报错，需要设置请求header

### ISSUE THREAD

**Issue by zhuyanhui** [FatDong1/cross-domain-demo#4]
按照你的代码通过http-proxy-middleware代理请求会报错ndex.html:1 Failed to load http://localhost:3000/api: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.  需要设置一下header加上这样一段代码 res.header("Access-Control-Allow-Origin", "*");

**Comment by rudyxu1102** [comment]
设置`res.header("Access-Control-Allow-Origin", "*");`属于CORS跨域，而这里是后端代理跨域的demo。

运行步骤：在demo2终端dos窗口输入`run.bat`

我试了一下，没有报错哦，你再试一下吧
