### ISSUE TITLE
Should CORS be abandoned?

### ISSUE THREAD

**Issue by jackzhp** [FatDong1/cross-domain-demo#5]
I think that CORS design is completely unnecessary, stupid, and so should be abandoned. I have laid down my arguments, if you think you know this issue pretty well, would you please look at it, and comment it.

https://github.com/jackzhp/CORS-should-retire
or
http://blog.sina.com.cn/s/blog_93b70ae70102wxe8.html

Hope you can contribute to the change!

**Comment by rudyxu1102** [comment]
Sorry, these demos is for beginning developer to get started. So I won't delete the CORS demo.
